language: java

env:
  global:
  - SBT_VER=1.2.6
    CMD=scripted

matrix:
  include:
   - scala: 2.12.7
     env: TRAVIS_SCALA_VERSION=2.12.7

   - scala: 2.10.7
     env: TRAVIS_SCALA_VERSION=2.10.7

script: /tmp/sbt/bin/sbt -Dsbt.version=$SBT_VER ++$TRAVIS_SCALA_VERSION $CMD

before_install:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS;
  - wget https://github.com/sbt/sbt/releases/download/v1.2.6/sbt-1.2.6.tgz
  - tar -xvf sbt-1.2.6.tgz
  - rm sbt-1.2.6.tgz
  - mv sbt /tmp/sbt

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/Library/Caches/Homebrew

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
